# Multi-variable Linear Regression

### linear regression 복습

* Hypothesis : H(x) = Wx + b
* Cost function : cost(W,b)
* Gradient descent algorithm : W - (cost(W)의 기울기)

### multi-label linear regression

* Hypothesis : H(x1,..,xn) = w1x1 + ... + wnxn + b
* Hypothesis using matrix : H(X) = XW (dot product이므로 순서 중요)
* Many x instances 일때도 하나의 긴 매트릭스에 W 곱해버리면 됨

![nn](images/matrix.png)

* instance는 5개, x변수는 3개, y변수는 1개
* instance를 n개로 설정하려면 numpy는 -1, tensorflow는 None로 설정

![nn](images/matrix_n.png)

* Wx와 XW의 수학적 의미는 같으나, tensorflow로 구현시 XW 순서 중요

# 실습

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### 일일이 코드로 구현

In [9]:
x1_data = [73,93,89,96,73]
x2_data = [80,88,91,98,66]
x3_data = [75,93,90,100,70]
y_data = [152,185,180,196,142]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 낮게
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                    feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, 'Prediction: ',hy_val)

0 Cost:  36086.324 Prediction:  [-14.305958 -19.813034 -17.8726   -20.759296 -15.122307]
10 Cost:  4.3419266 Prediction:  [153.72238 182.15878 181.12625 195.94632 138.93419]
20 Cost:  3.9911907 Prediction:  [154.22324 182.77505 181.72603 196.6003  139.40707]
30 Cost:  3.9709072 Prediction:  [154.21724 182.78206 181.72556 196.60062 139.41527]
40 Cost:  3.9507356 Prediction:  [154.20975 182.78722 181.72325 196.59895 139.42203]
50 Cost:  3.9306805 Prediction:  [154.20224 182.79233 181.72095 196.5973  139.42876]
60 Cost:  3.9106708 Prediction:  [154.19476 182.79747 181.71866 196.59564 139.4355 ]
70 Cost:  3.8908195 Prediction:  [154.18732 182.80258 181.71637 196.594   139.4422 ]
80 Cost:  3.871072 Prediction:  [154.17987 182.80768 181.71411 196.59235 139.44888]
90 Cost:  3.8514411 Prediction:  [154.17247 182.81276 181.71182 196.5907  139.45554]
100 Cost:  3.8318858 Prediction:  [154.16508 182.81784 181.70956 196.58907 139.4622 ]
110 Cost:  3.812481 Prediction:  [154.15773 182.82289 181.707

1500 Cost:  1.9202278 Prediction:  [153.30502 183.40741 181.44597 196.39854 140.2359 ]
1510 Cost:  1.9111259 Prediction:  [153.29999 183.41089 181.44443 196.39742 140.24043]
1520 Cost:  1.9020803 Prediction:  [153.29495 183.41432 181.44289 196.3963  140.24496]
1530 Cost:  1.8930798 Prediction:  [153.28993 183.41776 181.44133 196.39519 140.24947]
1540 Cost:  1.8841085 Prediction:  [153.28493 183.4212  181.4398  196.39407 140.25398]
1550 Cost:  1.8752136 Prediction:  [153.27995 183.42464 181.4383  196.393   140.25848]
1560 Cost:  1.8663709 Prediction:  [153.27496 183.42802 181.43675 196.39189 140.26294]
1570 Cost:  1.8575674 Prediction:  [153.27    183.43143 181.43524 196.3908  140.26741]
1580 Cost:  1.8487978 Prediction:  [153.26505 183.43483 181.43372 196.38968 140.27185]
1590 Cost:  1.8400757 Prediction:  [153.26012 183.4382  181.43219 196.38857 140.2763 ]
1600 Cost:  1.8314158 Prediction:  [153.25519 183.44159 181.4307  196.38751 140.28073]
1610 Cost:  1.8228159 Prediction:  [153.250

### Matrix로 구현

In [10]:
x_data = [[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]] # [5,3]
y_data = [[152],[185],[180],[196],[142]] # [5,1]

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                    feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, 'Prediction: ',hy_val)

0 Cost:  30796.406 Prediction:  [[ 0.60860336]
 [-5.4920893 ]
 [-1.9473125 ]
 [-6.137887  ]
 [-2.2597284 ]]
10 Cost:  8.225345 Prediction:  [[155.81927]
 [181.07784]
 [181.87366]
 [194.04033]
 [140.04921]]
20 Cost:  7.911044 Prediction:  [[156.27922]
 [181.6489 ]
 [182.42682]
 [194.64447]
 [140.48782]]
30 Cost:  7.8787775 Prediction:  [[156.271  ]
 [181.65717]
 [182.42545]
 [194.64476]
 [140.49718]]
40 Cost:  7.8466444 Prediction:  [[156.26134]
 [181.6637 ]
 [182.4224 ]
 [194.6432 ]
 [140.5052 ]]
50 Cost:  7.814723 Prediction:  [[156.25174]
 [181.67023]
 [182.41937]
 [194.6417 ]
 [140.5132 ]]
60 Cost:  7.782943 Prediction:  [[156.24216]
 [181.67674]
 [182.41634]
 [194.64017]
 [140.52116]]
70 Cost:  7.751297 Prediction:  [[156.23256]
 [181.68321]
 [182.41331]
 [194.63864]
 [140.52913]]
80 Cost:  7.7199006 Prediction:  [[156.22305]
 [181.6897 ]
 [182.41032]
 [194.63716]
 [140.53705]]
90 Cost:  7.6885757 Prediction:  [[156.21352]
 [181.69615]
 [182.40732]
 [194.63564]
 [140.54498]]
100 Co

840 Cost:  5.754387 Prediction:  [[155.56664]
 [182.13463]
 [182.2027 ]
 [194.53712]
 [141.07869]]
850 Cost:  5.733426 Prediction:  [[155.55884]
 [182.1399 ]
 [182.20024]
 [194.53596]
 [141.08505]]
860 Cost:  5.7124925 Prediction:  [[155.55106]
 [182.14517]
 [182.19777]
 [194.53484]
 [141.09142]]
870 Cost:  5.6917357 Prediction:  [[155.54332]
 [182.1504 ]
 [182.1953 ]
 [194.5337 ]
 [141.09776]]
880 Cost:  5.671032 Prediction:  [[155.53557]
 [182.15565]
 [182.19286]
 [194.53258]
 [141.10408]]
890 Cost:  5.6504297 Prediction:  [[155.52786]
 [182.16089]
 [182.1904 ]
 [194.5315 ]
 [141.11038]]
900 Cost:  5.629957 Prediction:  [[155.52014]
 [182.16608]
 [182.18794]
 [194.53035]
 [141.11665]]
910 Cost:  5.6096063 Prediction:  [[155.51248]
 [182.17128]
 [182.18552]
 [194.52925]
 [141.12292]]
920 Cost:  5.589318 Prediction:  [[155.50482]
 [182.17648]
 [182.1831 ]
 [194.52817]
 [141.12918]]
930 Cost:  5.5691657 Prediction:  [[155.49718]
 [182.18164]
 [182.18066]
 [194.52704]
 [141.1354 ]]
940 C

1660 Cost:  4.3470416 Prediction:  [[154.99042]
 [182.52429]
 [182.01927]
 [194.45752]
 [141.54527]]
1670 Cost:  4.3332767 Prediction:  [[154.98412]
 [182.52853]
 [182.01726]
 [194.45671]
 [141.55031]]
1680 Cost:  4.3196077 Prediction:  [[154.97784]
 [182.53278]
 [182.01526]
 [194.45589]
 [141.55533]]
1690 Cost:  4.305979 Prediction:  [[154.97157]
 [182.537  ]
 [182.01326]
 [194.45508]
 [141.56035]]
1700 Cost:  4.2924137 Prediction:  [[154.96532]
 [182.54121]
 [182.01125]
 [194.45427]
 [141.56532]]
1710 Cost:  4.278947 Prediction:  [[154.9591 ]
 [182.54543]
 [182.00925]
 [194.45346]
 [141.57031]]
1720 Cost:  4.2655497 Prediction:  [[154.95288]
 [182.54959]
 [182.00726]
 [194.45267]
 [141.57527]]
1730 Cost:  4.2521925 Prediction:  [[154.94669]
 [182.5538 ]
 [182.0053 ]
 [194.45187]
 [141.58022]]
1740 Cost:  4.2388864 Prediction:  [[154.94049]
 [182.55798]
 [182.00333]
 [194.4511 ]
 [141.58517]]
1750 Cost:  4.225713 Prediction:  [[154.93434]
 [182.56213]
 [182.00134]
 [194.45029]
 [141.5

# Loading data from file

### Using Numpy

In [15]:
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('datasets/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [16]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                    feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, 'Prediction: ',hy_val)

0 Cost:  94884.29 Prediction:  [[-133.5243 ]
 [-164.79396]
 [-160.21033]
 [-174.73906]
 [-126.36729]
 [ -93.72274]
 [-129.70605]
 [ -94.58198]
 [-155.14684]
 [-144.42427]
 [-125.9813 ]
 [-126.10946]
 [-165.43266]
 [-137.40392]
 [-130.9458 ]
 [-167.03172]
 [-131.88362]
 [-154.97739]
 [-157.01071]
 [-139.9864 ]
 [-152.77031]
 [-154.46288]
 [-145.2127 ]
 [-134.33794]
 [-170.08313]]
10 Cost:  20.48967 Prediction:  [[154.0632  ]
 [180.88208 ]
 [180.37784 ]
 [196.1936  ]
 [137.26738 ]
 [100.656654]
 [147.9531  ]
 [111.26122 ]
 [167.92491 ]
 [154.83463 ]
 [141.52913 ]
 [137.67375 ]
 [186.436   ]
 [155.09448 ]
 [147.99365 ]
 [183.75208 ]
 [146.682   ]
 [178.23947 ]
 [178.44128 ]
 [160.1619  ]
 [172.83008 ]
 [169.83232 ]
 [165.21791 ]
 [155.6048  ]
 [188.16367 ]]
20 Cost:  15.875616 Prediction:  [[156.0366 ]
 [183.27574]
 [182.72458]
 [198.75594]
 [139.09294]
 [102.01525]
 [149.87473]
 [112.69026]
 [170.17503]
 [156.93526]
 [143.3803 ]
 [139.51117]
 [188.85417]
 [157.09679]
 [149.9281 ]
 [186.1

790 Cost:  11.103734 Prediction:  [[155.16582 ]
 [183.6474  ]
 [182.32495 ]
 [198.74815 ]
 [139.37598 ]
 [103.04866 ]
 [150.10617 ]
 [113.151764]
 [171.37337 ]
 [159.1165  ]
 [143.58711 ]
 [140.50467 ]
 [188.02888 ]
 [155.89502 ]
 [150.41974 ]
 [186.83871 ]
 [147.3644  ]
 [180.76393 ]
 [179.6691  ]
 [161.1833  ]
 [175.40742 ]
 [172.75781 ]
 [167.42943 ]
 [155.73514 ]
 [190.5993  ]]
800 Cost:  11.060777 Prediction:  [[155.1562  ]
 [183.65126 ]
 [182.32043 ]
 [198.74788 ]
 [139.3789  ]
 [103.059784]
 [150.10857 ]
 [113.15668 ]
 [171.38622 ]
 [159.14005 ]
 [143.58922 ]
 [140.51532 ]
 [188.01973 ]
 [155.8818  ]
 [150.42494 ]
 [186.84563 ]
 [147.35095 ]
 [180.76614 ]
 [179.65727 ]
 [161.17189 ]
 [175.41077 ]
 [172.76497 ]
 [167.42998 ]
 [155.71494 ]
 [190.59871 ]]
810 Cost:  11.018194 Prediction:  [[155.14664 ]
 [183.65509 ]
 [182.31593 ]
 [198.74759 ]
 [139.3818  ]
 [103.070854]
 [150.1109  ]
 [113.16157 ]
 [171.39899 ]
 [159.16347 ]
 [143.59131 ]
 [140.52591 ]
 [188.01062 ]
 [155.86865 ]


1600 Cost:  8.611935 Prediction:  [[154.51106 ]
 [183.90979 ]
 [182.01686 ]
 [198.7295  ]
 [139.57515 ]
 [103.806496]
 [150.26857 ]
 [113.487785]
 [172.24887 ]
 [160.72133 ]
 [143.73094 ]
 [141.23085 ]
 [187.40486 ]
 [154.99379 ]
 [150.77464 ]
 [187.30992 ]
 [146.447   ]
 [180.91597 ]
 [178.86221 ]
 [160.40514 ]
 [175.63597 ]
 [173.2459  ]
 [167.46805 ]
 [154.35846 ]
 [190.55746 ]]
1610 Cost:  8.590998 Prediction:  [[154.50436]
 [183.91248]
 [182.0137 ]
 [198.72931]
 [139.57718]
 [103.81424]
 [150.27023]
 [113.49124]
 [172.25783]
 [160.73775]
 [143.73242]
 [141.23825]
 [187.39847]
 [154.98456]
 [150.77826]
 [187.31476]
 [146.4376 ]
 [180.91754]
 [178.85394]
 [160.39716]
 [175.6383 ]
 [173.25089]
 [167.46844]
 [154.34436]
 [190.55704]]
1620 Cost:  8.570276 Prediction:  [[154.4977  ]
 [183.91515 ]
 [182.01057 ]
 [198.72911 ]
 [139.5792  ]
 [103.82196 ]
 [150.2719  ]
 [113.494675]
 [172.26674 ]
 [160.7541  ]
 [143.73387 ]
 [141.24565 ]
 [187.3921  ]
 [154.97536 ]
 [150.78188 ]
 [187.31953

In [17]:
print('Your score will be ', sess.run(hypothesis, 
                                      feed_dict={X:[[100,70,101]]}))
print('Others score will be ', sess.run(hypothesis, 
                                feed_dict={X:[[60,70,110],[90,100,80]]}))

Your score will be  [[181.11592]]
Others score will be  [[174.52684]
 [179.49312]]


### Using Queue Runners

(1) file queue 스택 쌓기

In [27]:
filename_queue = tf.train.string_input_producer(\
            ['datasets/data-01-test-score.csv','datasets/data-02-test-score'],\
            shuffle=False, name='filename_queue')

(2) file을 읽어올 reader를 정의

In [28]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

(3) 읽어올 value를 어떻게 parcing할 것인지 정의

In [29]:
record_defaults = [[0,],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

(4) batch를 이용해 데이터 읽어오기(펌프처럼 데이터 빨아옴)

In [30]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]],\
                        batch_size=10) # 한번 펌프할 때 10개씩 가져와라

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                    feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, 'Prediction: ', hy_val)
    
coord.request_stop()
coord.join(threads)

TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float32'> to <dtype: 'int32'> (Tensor is: <tf.Tensor 'DecodeCSV_2:1' shape=() dtype=float32>)

### shuffle_batch

In [31]:
min_after_dequeue = 10000
capacity = min_after_dequeue + 3*batch_size
example_batch, label_batch = tf.train.shuffle_batch(
            [example, label], batch_size=batch_size, capacity=capacity,
            min_after_dequeue=min_after_dequeue)

NameError: name 'batch_size' is not defined